version: '3'
services:
  postgres:
    container_name: quarkus-postgresdb
    image: postgres:alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "pocquarkus"
    networks:
      - poc-quarkus-network
  sample:
    container_name: sample
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - poc-quarkus-network
  quarkus-api:
    restart: on-failure
    build:
      dockerfile: Dockerfile.jvm
      context: .
    image: pocquarkus/api-jvm
    container_name: quarkus-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - poc-quarkus-network
networks:
  poc-quarkus-network:
    driver: bridge
