version: '3'
services:  
  sample:
    container_name: react
    restart: on-failure
    build:
      context: react
      dockerfile: Dockerfile    
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - poc-quarkus-network
    image: pocquarkus/react
  quarkus-api:
    restart: on-failure
    build:
      dockerfile: Dockerfile.jvm
      context: poc-quarkus
    image: pocquarkus/api-jvm
    container_name: quarkus-api
    ports:
      - "8080:8080"
    networks:
      - poc-quarkus-network
networks:
  poc-quarkus-network:
    driver: bridge
  
      
